### ISSUE TITLE
Дружище, ты гений

### ISSUE THREAD

**Issue by MaestroDi** [aleksan149/PC_keyboard_BAYAN#1]
А есть для винды скомпилированная? так хочется поиграть на двух клавиатурах, недавно начал учиться на баяне

**Comment by aleksan149** [comment]
Привет! для винды нету, все руки не доходят сделать. Можно из исходников запустить на винде)

**Comment by MaestroDi** [comment]
Я в программировании мало что понимаю, просто искал программу виртуального баяна, сюда наткнулся. Что мне сделать чтобы запустить?

**Comment by aleksan149** [comment]
Если в кратце, то ставишь с оф сайта питон, к нему устанавливаешь библиотеку pgzero. через командную строку это выглядит както так pip3 install pgzero.  Скачиваешь весь мой репозитороий с баяном. Заходишь в папку с ним через терминал и запускаешь python3 PC_keyboard_BAYAN.py
Или устанавливаешь pycharm, открываешь в нем как проект мой репозиторий и запускаешь прям в нем, если не знаком с терминалом. библиотеку pgzero тоже в нем можно поставить. 
Я когдато соберу под виндду этот баян, но с виндой это всегда компилируется както сложно)
если что пиши в тг @serg_ipsecov

**Comment by MaestroDi** [comment]
О, сенк, буду пробовать
